apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-dns-corefile
  namespace: internal-dns
data:
  Corefile: |
    home.internal:53 {
      log
      errors
      file /etc/coredns/zones/home.internal.db home.internal
      header {
        response set ra
      }
    }

    .:53 {
      log
      errors
      health
      ready
      cache 30
      forward . 1.214.68.2 61.41.153.2
    }
